--------------------------------------------------------
--  DDL for Table BANCO
--------------------------------------------------------

  CREATE TABLE "ADMINLOL"."BANCO" 
   (	"IDBANCO" NUMBER(*,0), 
	"DOMICILIO" VARCHAR2(100 BYTE), 
	"NOMBRE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "ADMINLOL"."BANCO"."IDBANCO" IS 'Asignamos un id único a cada banco.';
 
   COMMENT ON COLUMN "ADMINLOL"."BANCO"."DOMICILIO" IS 'Contiene el domicilio del banco.';
 
   COMMENT ON COLUMN "ADMINLOL"."BANCO"."NOMBRE" IS 'Contiene el nombre por el que es conocido el banco.';
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "ADMINLOL"."CLIENTE" 
   (	"IDCLIENTE" NUMBER(*,0), 
	"NOMBRECLIENTE" VARCHAR2(50 BYTE), 
	"CONTACTO" VARCHAR2(50 BYTE), 
	"RFC" VARCHAR2(13 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "ADMINLOL"."CLIENTE"."IDCLIENTE" IS 'Identificación de clientes.';
 
   COMMENT ON COLUMN "ADMINLOL"."CLIENTE"."NOMBRECLIENTE" IS 'Nombre completo del cliente.';
 
   COMMENT ON COLUMN "ADMINLOL"."CLIENTE"."CONTACTO" IS 'Correo electrónico del cliente.';
 
   COMMENT ON COLUMN "ADMINLOL"."CLIENTE"."RFC" IS 'Clave RFC del cliente.';
--------------------------------------------------------
--  DDL for Table CUENTA
--------------------------------------------------------

  CREATE TABLE "ADMINLOL"."CUENTA" 
   (	"IDBANCO" NUMBER(*,0), 
	"IDCUENTA" NUMBER(*,0), 
	"IDCLIENTE" NUMBER(*,0), 
	"IDTIPOCUENTA" NUMBER(*,0), 
	"NUMEROCUENTA" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "ADMINLOL"."CUENTA"."IDBANCO" IS 'Identificación única de la sucursal bancaria.';
 
   COMMENT ON COLUMN "ADMINLOL"."CUENTA"."IDCUENTA" IS 'Identificación única de cada cuenta.';
 
   COMMENT ON COLUMN "ADMINLOL"."CUENTA"."IDCLIENTE" IS 'Identificación única de cada cliente.';
 
   COMMENT ON COLUMN "ADMINLOL"."CUENTA"."IDTIPOCUENTA" IS 'Identificación de cada tipo de cuenta.';
 
   COMMENT ON COLUMN "ADMINLOL"."CUENTA"."NUMEROCUENTA" IS 'Número de cuenta para referencia interna.';
--------------------------------------------------------
--  DDL for Table TIPOCUENTA
--------------------------------------------------------

  CREATE TABLE "ADMINLOL"."TIPOCUENTA" 
   (	"IDTIPOCUENTA" NUMBER(*,0), 
	"TIPOCUENTA" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "ADMINLOL"."TIPOCUENTA"."IDTIPOCUENTA" IS 'Toma valores dependiendo del tipo de cuenta.';
 
   COMMENT ON COLUMN "ADMINLOL"."TIPOCUENTA"."TIPOCUENTA" IS 'Representación legible del tipo de cuenta correspondiente.';
--------------------------------------------------------
--  DDL for Table TRANSACCIONES
--------------------------------------------------------

  CREATE TABLE "ADMINLOL"."TRANSACCIONES" 
   (	"IDTRANSACCION" NUMBER(*,0), 
	"IDBANCO" NUMBER(*,0), 
	"IDCUENTA" NUMBER(*,0), 
	"NUMEROCUENTA" NUMBER(*,0), 
	"TIPOTRANSACCION" VARCHAR2(20 BYTE), 
	"RETIRO" NUMBER(*,0), 
	"DEPOSITO" NUMBER(*,0), 
	"MONTO" NUMBER(*,0), 
	"FECHA" DATE, 
	"IDCLIENTE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "ADMINLOL"."TRANSACCIONES"."IDTRANSACCION" IS 'Identificación unica para cada transacción';
 
   COMMENT ON COLUMN "ADMINLOL"."TRANSACCIONES"."IDBANCO" IS 'Identificación única para cada sucursal bancaria.';
 
   COMMENT ON COLUMN "ADMINLOL"."TRANSACCIONES"."IDCUENTA" IS 'Identificación única para cada cuenta.';
 
   COMMENT ON COLUMN "ADMINLOL"."TRANSACCIONES"."NUMEROCUENTA" IS 'Número de cuenta para control y referencia internas.';
 
   COMMENT ON COLUMN "ADMINLOL"."TRANSACCIONES"."TIPOTRANSACCION" IS 'Representación legible del tipo de transacción.';
 
   COMMENT ON COLUMN "ADMINLOL"."TRANSACCIONES"."RETIRO" IS 'Cantidad retirada en la operación.';
 
   COMMENT ON COLUMN "ADMINLOL"."TRANSACCIONES"."DEPOSITO" IS 'Cantidad depositada en la operación.';
 
   COMMENT ON COLUMN "ADMINLOL"."TRANSACCIONES"."MONTO" IS 'Cantidad generada (trigger) haciendo la diferencia entre depósito y retiro al momento de la inserción.';
 
   COMMENT ON COLUMN "ADMINLOL"."TRANSACCIONES"."FECHA" IS 'Generada a partir de la fecha del sistema (trigger) al momento de inserción.';
 
   COMMENT ON COLUMN "ADMINLOL"."TRANSACCIONES"."IDCLIENTE" IS 'Identificación única del cliente.';

   --------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "ADMINLOL"."CLIENTE" MODIFY ("IDCLIENTE" NOT NULL ENABLE);
 
  ALTER TABLE "ADMINLOL"."CLIENTE" MODIFY ("NOMBRECLIENTE" NOT NULL ENABLE);
 
  ALTER TABLE "ADMINLOL"."CLIENTE" MODIFY ("CONTACTO" NOT NULL ENABLE);
 
  ALTER TABLE "ADMINLOL"."CLIENTE" MODIFY ("RFC" NOT NULL ENABLE);
 
  ALTER TABLE "ADMINLOL"."CLIENTE" ADD PRIMARY KEY ("IDCLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BANCO
--------------------------------------------------------

  ALTER TABLE "ADMINLOL"."BANCO" MODIFY ("IDBANCO" NOT NULL ENABLE);
 
  ALTER TABLE "ADMINLOL"."BANCO" MODIFY ("DOMICILIO" NOT NULL ENABLE);
 
  ALTER TABLE "ADMINLOL"."BANCO" ADD PRIMARY KEY ("IDBANCO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "ADMINLOL"."BANCO" MODIFY ("NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CUENTA
--------------------------------------------------------

  ALTER TABLE "ADMINLOL"."CUENTA" MODIFY ("IDBANCO" NOT NULL ENABLE);
 
  ALTER TABLE "ADMINLOL"."CUENTA" MODIFY ("IDCUENTA" NOT NULL ENABLE);
 
  ALTER TABLE "ADMINLOL"."CUENTA" MODIFY ("IDCLIENTE" NOT NULL ENABLE);
 
  ALTER TABLE "ADMINLOL"."CUENTA" MODIFY ("IDTIPOCUENTA" NOT NULL ENABLE);
 
  ALTER TABLE "ADMINLOL"."CUENTA" MODIFY ("NUMEROCUENTA" NOT NULL ENABLE);
 
  ALTER TABLE "ADMINLOL"."CUENTA" ADD PRIMARY KEY ("IDCUENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRANSACCIONES
--------------------------------------------------------

  ALTER TABLE "ADMINLOL"."TRANSACCIONES" MODIFY ("IDTRANSACCION" NOT NULL ENABLE);
 
  ALTER TABLE "ADMINLOL"."TRANSACCIONES" MODIFY ("IDBANCO" NOT NULL ENABLE);
 
  ALTER TABLE "ADMINLOL"."TRANSACCIONES" MODIFY ("IDCUENTA" NOT NULL ENABLE);
 
  ALTER TABLE "ADMINLOL"."TRANSACCIONES" MODIFY ("NUMEROCUENTA" NOT NULL ENABLE);
 
  ALTER TABLE "ADMINLOL"."TRANSACCIONES" MODIFY ("RETIRO" NOT NULL ENABLE);
 
  ALTER TABLE "ADMINLOL"."TRANSACCIONES" MODIFY ("DEPOSITO" NOT NULL ENABLE);
 
  ALTER TABLE "ADMINLOL"."TRANSACCIONES" MODIFY ("TIPOTRANSACCION" NOT NULL ENABLE);
 
  ALTER TABLE "ADMINLOL"."TRANSACCIONES" ADD CONSTRAINT "TRANSACCIONES_PK" PRIMARY KEY ("IDTRANSACCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TIPOCUENTA
--------------------------------------------------------

  ALTER TABLE "ADMINLOL"."TIPOCUENTA" MODIFY ("IDTIPOCUENTA" NOT NULL ENABLE);
 
  ALTER TABLE "ADMINLOL"."TIPOCUENTA" MODIFY ("TIPOCUENTA" NOT NULL ENABLE);
 
  ALTER TABLE "ADMINLOL"."TIPOCUENTA" ADD PRIMARY KEY ("IDTIPOCUENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CUENTA
--------------------------------------------------------

  ALTER TABLE "ADMINLOL"."CUENTA" ADD CONSTRAINT "CUENTA_BANCO_FK" FOREIGN KEY ("IDBANCO")
    REFERENCES "ADMINLOL"."BANCO" ("IDBANCO") ENABLE;
 
  ALTER TABLE "ADMINLOL"."CUENTA" ADD CONSTRAINT "CUENTA_CLIENTE_FK" FOREIGN KEY ("IDCLIENTE")
    REFERENCES "ADMINLOL"."CLIENTE" ("IDCLIENTE") ENABLE;
 
  ALTER TABLE "ADMINLOL"."CUENTA" ADD CONSTRAINT "CUENTA_TIPOCUENTA_FK" FOREIGN KEY ("IDTIPOCUENTA")
    REFERENCES "ADMINLOL"."TIPOCUENTA" ("IDTIPOCUENTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRANSACCIONES
--------------------------------------------------------

  ALTER TABLE "ADMINLOL"."TRANSACCIONES" ADD CONSTRAINT "TRANSACCIONES_BANCO_FK" FOREIGN KEY ("IDBANCO")
    REFERENCES "ADMINLOL"."BANCO" ("IDBANCO") ENABLE;
 
  ALTER TABLE "ADMINLOL"."TRANSACCIONES" ADD CONSTRAINT "TRANSACCIONES_CLIENTE" FOREIGN KEY ("IDCLIENTE")
    REFERENCES "ADMINLOL"."CLIENTE" ("IDCLIENTE") ON DELETE SET NULL ENABLE;
 
  ALTER TABLE "ADMINLOL"."TRANSACCIONES" ADD CONSTRAINT "TRANSACCIONES_CUENTA_FK" FOREIGN KEY ("IDCUENTA")
    REFERENCES "ADMINLOL"."CUENTA" ("IDCUENTA") ENABLE;
--------------------------------------------------------